import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
  BulmaM0Directive,
  BulmaM1Directive,
  BulmaM2Directive,
  BulmaM3Directive,
  BulmaM4Directive,
  BulmaM5Directive,
  BulmaM6Directive,
} from './margin.directive';

import {
  BulmaMt0Directive,
  BulmaMt1Directive,
  BulmaMt2Directive,
  BulmaMt3Directive,
  BulmaMt4Directive,
  BulmaMt5Directive,
  BulmaMt6Directive,
} from './margin-top.directive';

import {
  BulmaMr0Directive,
  BulmaMr1Directive,
  BulmaMr2Directive,
  BulmaMr3Directive,
  BulmaMr4Directive,
  BulmaMr5Directive,
  BulmaMr6Directive,
} from './margin-right.directive';

import {
  BulmaMb0Directive,
  BulmaMb1Directive,
  BulmaMb2Directive,
  BulmaMb3Directive,
  BulmaMb4Directive,
  BulmaMb5Directive,
  BulmaMb6Directive,
} from './margin-bottom.directive';

import {
  BulmaMl0Directive,
  BulmaMl1Directive,
  BulmaMl2Directive,
  BulmaMl3Directive,
  BulmaMl4Directive,
  BulmaMl5Directive,
  BulmaMl6Directive,
} from './margin-left.directive';

import {
  BulmaMx0Directive,
  BulmaMx1Directive,
  BulmaMx2Directive,
  BulmaMx3Directive,
  BulmaMx4Directive,
  BulmaMx5Directive,
  BulmaMx6Directive,
} from './margin-left-right.directive';

import {
  BulmaMy0Directive,
  BulmaMy1Directive,
  BulmaMy2Directive,
  BulmaMy3Directive,
  BulmaMy4Directive,
  BulmaMy5Directive,
  BulmaMy6Directive,
} from './margin-top-bottom.directive';

import {
  BulmaP0Directive,
  BulmaP1Directive,
  BulmaP2Directive,
  BulmaP3Directive,
  BulmaP4Directive,
  BulmaP5Directive,
  BulmaP6Directive,
} from './padding.directive';

import {
  BulmaPt0Directive,
  BulmaPt1Directive,
  BulmaPt2Directive,
  BulmaPt3Directive,
  BulmaPt4Directive,
  BulmaPt5Directive,
  BulmaPt6Directive,
} from './padding-top.directive';

import {
  BulmaPr0Directive,
  BulmaPr1Directive,
  BulmaPr2Directive,
  BulmaPr3Directive,
  BulmaPr4Directive,
  BulmaPr5Directive,
  BulmaPr6Directive,
} from './padding-right.directive';

import {
  BulmaPb0Directive,
  BulmaPb1Directive,
  BulmaPb2Directive,
  BulmaPb3Directive,
  BulmaPb4Directive,
  BulmaPb5Directive,
  BulmaPb6Directive,
} from './padding-bottom.directive';

import {
  BulmaPl0Directive,
  BulmaPl1Directive,
  BulmaPl2Directive,
  BulmaPl3Directive,
  BulmaPl4Directive,
  BulmaPl5Directive,
  BulmaPl6Directive,
} from './padding-left.directive';

import {
  BulmaPx0Directive,
  BulmaPx1Directive,
  BulmaPx2Directive,
  BulmaPx3Directive,
  BulmaPx4Directive,
  BulmaPx5Directive,
  BulmaPx6Directive,
} from './padding-left-right.directive';

import {
  BulmaPy0Directive,
  BulmaPy1Directive,
  BulmaPy2Directive,
  BulmaPy3Directive,
  BulmaPy4Directive,
  BulmaPy5Directive,
  BulmaPy6Directive,
} from './padding-top-bottom.directive';

@NgModule({
  imports: [CommonModule],
  declarations: [
    BulmaM0Directive,
    BulmaM1Directive,
    BulmaM2Directive,
    BulmaM3Directive,
    BulmaM4Directive,
    BulmaM5Directive,
    BulmaM6Directive,
    BulmaMt0Directive,
    BulmaMt1Directive,
    BulmaMt2Directive,
    BulmaMt3Directive,
    BulmaMt4Directive,
    BulmaMt5Directive,
    BulmaMt6Directive,
    BulmaMr0Directive,
    BulmaMr1Directive,
    BulmaMr2Directive,
    BulmaMr3Directive,
    BulmaMr4Directive,
    BulmaMr5Directive,
    BulmaMr6Directive,
    BulmaMb0Directive,
    BulmaMb1Directive,
    BulmaMb2Directive,
    BulmaMb3Directive,
    BulmaMb4Directive,
    BulmaMb5Directive,
    BulmaMb6Directive,
    BulmaMl0Directive,
    BulmaMl1Directive,
    BulmaMl2Directive,
    BulmaMl3Directive,
    BulmaMl4Directive,
    BulmaMl5Directive,
    BulmaMl6Directive,
    BulmaMx0Directive,
    BulmaMx1Directive,
    BulmaMx2Directive,
    BulmaMx3Directive,
    BulmaMx4Directive,
    BulmaMx5Directive,
    BulmaMx6Directive,
    BulmaMy0Directive,
    BulmaMy1Directive,
    BulmaMy2Directive,
    BulmaMy3Directive,
    BulmaMy4Directive,
    BulmaMy5Directive,
    BulmaMy6Directive,
    BulmaP0Directive,
    BulmaP1Directive,
    BulmaP2Directive,
    BulmaP3Directive,
    BulmaP4Directive,
    BulmaP5Directive,
    BulmaP6Directive,
    BulmaPt0Directive,
    BulmaPt1Directive,
    BulmaPt2Directive,
    BulmaPt3Directive,
    BulmaPt4Directive,
    BulmaPt5Directive,
    BulmaPt6Directive,
    BulmaPr0Directive,
    BulmaPr1Directive,
    BulmaPr2Directive,
    BulmaPr3Directive,
    BulmaPr4Directive,
    BulmaPr5Directive,
    BulmaPr6Directive,
    BulmaPb0Directive,
    BulmaPb1Directive,
    BulmaPb2Directive,
    BulmaPb3Directive,
    BulmaPb4Directive,
    BulmaPb5Directive,
    BulmaPb6Directive,
    BulmaPl0Directive,
    BulmaPl1Directive,
    BulmaPl2Directive,
    BulmaPl3Directive,
    BulmaPl4Directive,
    BulmaPl5Directive,
    BulmaPl6Directive,
    BulmaPx0Directive,
    BulmaPx1Directive,
    BulmaPx2Directive,
    BulmaPx3Directive,
    BulmaPx4Directive,
    BulmaPx5Directive,
    BulmaPx6Directive,
    BulmaPy0Directive,
    BulmaPy1Directive,
    BulmaPy2Directive,
    BulmaPy3Directive,
    BulmaPy4Directive,
    BulmaPy5Directive,
    BulmaPy6Directive,
  ],
  exports: [
    BulmaM0Directive,
    BulmaM1Directive,
    BulmaM2Directive,
    BulmaM3Directive,
    BulmaM4Directive,
    BulmaM5Directive,
    BulmaM6Directive,
    BulmaMt0Directive,
    BulmaMt1Directive,
    BulmaMt2Directive,
    BulmaMt3Directive,
    BulmaMt4Directive,
    BulmaMt5Directive,
    BulmaMt6Directive,
    BulmaMr0Directive,
    BulmaMr1Directive,
    BulmaMr2Directive,
    BulmaMr3Directive,
    BulmaMr4Directive,
    BulmaMr5Directive,
    BulmaMr6Directive,
    BulmaMb0Directive,
    BulmaMb1Directive,
    BulmaMb2Directive,
    BulmaMb3Directive,
    BulmaMb4Directive,
    BulmaMb5Directive,
    BulmaMb6Directive,
    BulmaMl0Directive,
    BulmaMl1Directive,
    BulmaMl2Directive,
    BulmaMl3Directive,
    BulmaMl4Directive,
    BulmaMl5Directive,
    BulmaMl6Directive,
    BulmaMx0Directive,
    BulmaMx1Directive,
    BulmaMx2Directive,
    BulmaMx3Directive,
    BulmaMx4Directive,
    BulmaMx5Directive,
    BulmaMx6Directive,
    BulmaMy0Directive,
    BulmaMy1Directive,
    BulmaMy2Directive,
    BulmaMy3Directive,
    BulmaMy4Directive,
    BulmaMy5Directive,
    BulmaMy6Directive,
    BulmaP0Directive,
    BulmaP1Directive,
    BulmaP2Directive,
    BulmaP3Directive,
    BulmaP4Directive,
    BulmaP5Directive,
    BulmaP6Directive,
    BulmaPt0Directive,
    BulmaPt1Directive,
    BulmaPt2Directive,
    BulmaPt3Directive,
    BulmaPt4Directive,
    BulmaPt5Directive,
    BulmaPt6Directive,
    BulmaPr0Directive,
    BulmaPr1Directive,
    BulmaPr2Directive,
    BulmaPr3Directive,
    BulmaPr4Directive,
    BulmaPr5Directive,
    BulmaPr6Directive,
    BulmaPb0Directive,
    BulmaPb1Directive,
    BulmaPb2Directive,
    BulmaPb3Directive,
    BulmaPb4Directive,
    BulmaPb5Directive,
    BulmaPb6Directive,
    BulmaPl0Directive,
    BulmaPl1Directive,
    BulmaPl2Directive,
    BulmaPl3Directive,
    BulmaPl4Directive,
    BulmaPl5Directive,
    BulmaPl6Directive,
    BulmaPx0Directive,
    BulmaPx1Directive,
    BulmaPx2Directive,
    BulmaPx3Directive,
    BulmaPx4Directive,
    BulmaPx5Directive,
    BulmaPx6Directive,
    BulmaPy0Directive,
    BulmaPy1Directive,
    BulmaPy2Directive,
    BulmaPy3Directive,
    BulmaPy4Directive,
    BulmaPy5Directive,
    BulmaPy6Directive,
  ]
})
export class BulmaSpacingDirectivesModule {}
