name: Angular-Bulma Testing
on:
  push: { develop, bugfix/*, feature/*, release/*, hotfix/*, support/* }
  release:
    types:
      - created
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.22.2
          run_install: true
      - run: pnpm run ng components:test -- --ci
